### ISSUE TITLE
Can i just run the Batch process with Python in the cmd console ?

### ISSUE THREAD

**Issue by feng-1985** [houking-can/pdf2html#2]
it raise the following errors:
![image](https://user-images.githubusercontent.com/8215563/64684930-9f1c1700-d4b8-11e9-8d39-0dc634e74c92.png)

system:
win 10

**Comment by houking-can** [comment]
You need install Adobe Acrobat, and you can run Batch process.

**Comment by feng-1985** [comment]
I have installed, is there any recommended version  or dowload links ? Did you use the cracked version ?
![image](https://user-images.githubusercontent.com/8215563/64751914-5c0d8280-d550-11e9-925b-246defd39f83.png)

**Comment by houking-can** [comment]
The version I use is Adobe Acrobat Pro DC，Reader DC can not export PDF to other format. I am using a trial version.

**Comment by feng-1985** [comment]
Thanks! 👍
